---
- name: maven settings for QA CentOS machine
  hosts: qa
  sudo: true
  tasks:
    - name: unpack maven compressed file
      unarchive: >
        src=/home/kiarash/install/dev/apache/maven/apache-maven-3.2.2-bin.tar.gz
        dest=/opt/
    - name: create maven link
      file: src=/opt/apache-maven-3.2.2 dest=/opt/maven state=link
    - name: set maven environment
      copy: src=files/maven.sh dest=/etc/profile.d/maven.sh
